### ISSUE TITLE
Cannot ping 192.168.144.25 after setting up eth0

### ISSUE THREAD

**Issue by lherlein** [julianoes/siyi-a8-mini-camera-manager#28]
Hi there,

I am following the intro instructions and have: 
1. My powered Siyi a8 mini connected to the ethernet port of my rPi. 
2. I successfully used NetworkManager to configure the eth0 port
3. I see the same result listed when using `ip addr`
4. `ping 192.168.144.20` packets returns fine
5. `ping 192.168.144.25` all packets timeout

What could I be doing wrong here? The ethernet -> Siyi wire I'm using uses 4/9 pins on the Siyi side. I am using a 3 cell 50C lipo, fully charged, to power the Siyi. 

Any help is much appreciated! Thanks in advance!

Best,
Luca

**Comment by lherlein** [comment]
I believe I found the issue here - the NetworkManager command in the readme sets the gateway to `24`, which should be fine... but when I changed the gateway manually to `255.255.255.0` things started to work. I'm not sure why this is the case but it fixed my problem if anyone else runs into this

**Comment by julianoes** [comment]
Oh ok. Can you make a pull request for the change you suggest?

Edit: And thanks!

**Comment by lherlein** [comment]
Absolutely - will get to that within this week
