### ISSUE TITLE
camera_manager cli --connection input

### ISSUE THREAD

**Issue by lherlein** [julianoes/siyi-a8-mini-camera-manager#29]
I'm wondering if you could explain this line : "How MAVSDK should connect to the Pixhawk, for serial: `serial:///dev/serial/to/pixhawk:baudrate`". I'm confused about the `/serial/to/pixhawk`. Are the slashes here indicative of a path? I've ran the command with both `/dev/serial0` and `/dev/ttyAMA0`, and both commands are accepted and run, but then the connection to QGroundControl does not work.

How I'm starting the `camera_manager` script:

`camera-manager/build/camera_manager --connection serial:///dev/serial0:3000000 --forwarding 'on' --stream-url 192.168.2.112`

or 

`camera-manager/build/camera_manager --connection serial:///dev/ttyAMA0:3000000 --forwarding 'on' --stream-url 192.168.2.112`

If those look correct, what are some other troubleshooting steps I can take to understand why qgroundcontrol doesn't auto-connect to my setup? 

Thanks for the help, and sorry for multiple questions. Excited to get this working!

**Comment by lherlein** [comment]
Update: camera_manager app sends debug output: 
```
Taking a picture (2309)...
Mavsdk debug: sent camera image captured msg - index: 2983 (camera_server_impl.cpp:359)
Mavsdk debug: received image start capture request - interval: 0 total: 1 index: 2310 (camera_server_impl.cpp:1441)
```

The stream definitely works (verified w/ ffmpeg). Video enabled in QGC. I can see the image Mavlink messages coming through in the Mavlink message inspector. However, QGC just doesn't want to play the video, showing 'waiting for video'. Any insight?

**Comment by julianoes** [comment]
Is the rtsp_rebroadcast working? Can you try it just by using a video player, e.g.:

Where `192.168.1.23` is the IP of your Pi where rtsp_rebroadcast runs.
```
ffplay rtsp://192.168.1.23:8554/live
```
or:
```
gst-play-1.0 rtsp://192.168.1.23:8554/live
```

**Comment by lherlein** [comment]
@julianoes Yes, the RTSP rebroadcast works great. I can watch the video using ffmpeg. I also can see the mavlink connection between camera_manager and my pixhawk. Something I noticed is that QGC is requesting pictures, not a video - when I switch to the 'picture' mode in QGC, I can see the picture index from the debug messages coming across (can get a screenshot if necessary). Even still, QGC doesn't show the images that are actually being taken.

**Comment by julianoes** [comment]
Have you set the `--stream-url` argument correctly? That's what QGC will use to connect to the RTSP stream.

QGC doesn't have any way of downloading pictures. All it would do is to show the live RTSP feed.

**Comment by lherlein** [comment]
I set the `--stream-url` to the raw IP of where my stream is, not the full rtsp url. I'll try with the full URL. I'll also take a screenshot of what I'm seeing in the 'images' tab on QGC - it's not downloading them but seems to know they're there

**Comment by lherlein** [comment]
![Screenshot from 2024-11-09 17-42-04](https://github.com/user-attachments/assets/fe0bcb00-031d-4d06-b81d-00978ceba2d5)

Here you can see the mavsdk debug message that says it's sending a camera image captured msg (this message repeats very quickly). This is being output on the raspberry pi running the camera manager and rtsp-rebroadcast. The number underneath the record button in QGC increments with the index that mavsdk debugger. 

I tried with both --stream-url types: `192.168.2.112` and `rtsp://192.168.2.112:8554/live` . Neither one fixed the problem. @julianoes Any idea what could be causing this?

**Comment by lherlein** [comment]
Here's my command and the start of the debug output:

```
luca@raspberrypi:~/siyi-a8-mini-camera-manager $ camera-manager/build/camera_manager --connection serial:///dev/ttyAMA0:3000000 --forwarding 'on' --stream-url 192.168.2.112
[03:47:51|Info ] MAVSDK version: v2.12.4 (mavsdk_impl.cpp:26)
Created connection 'serial:///dev/ttyAMA0:3000000' forwarding 'on'
Using FTP root: ./camera-manager/mavlink_ftp_root to serve camera xml file.
Mavsdk debug: New system ID: 1 Comp ID: 1 (mavsdk_impl.cpp:720)
Mavsdk debug: Component Autopilot (1) added. (system_impl.cpp:366)
Mavsdk debug: received image start capture request - interval: 0 total: 1 index: 13665 (camera_server_impl.cpp:1441)
Taking a picture (13665)...
Mavsdk debug: sent camera image captured msg - index: 0 (camera_server_impl.cpp:359)
Mavsdk debug: received image start capture request - interval: 0 total: 1 index: 13666 (camera_server_impl.cpp:1441)
```

After multiple camera image requested/camera image sent requests:

```
Mavsdk debug: New system ID: 255 Comp ID: 190 (mavsdk_impl.cpp:720)
Mavsdk debug: Component Ground station (190) added. (system_impl.cpp:366)
```

As far as I can tell these are the debug messages that aren't image request/capture.

**Comment by julianoes** [comment]
> [03:47:51|Info ] MAVSDK version: v2.12.4 (mavsdk_impl.cpp:26)

Make sure to use the latest MAVSDK release.

> Any idea what could be causing this?

The URL that you supply, does it work directly when you try it?

Can you double check that the [VIDEO_STREAM_INFORMATION](https://mavlink.io/en/messages/common.html#VIDEO_STREAM_INFORMATION).uri is correct when you receive it in QGC (check MAVLink Inspector).

**Comment by julianoes** [comment]
Also, is it possible that you have enabled MAVLink forwaring on the PX4 between QGC and the gimbal serial? If so, try without. Otherwise the SIYI "MAVLink camera" will interfere with this camera manager.

**Comment by lherlein** [comment]
Okay - so if I let the mavlink inspector sit for about 1-2 minutes after boot then I see the VIDEO_STREAM_INFORMATION and CAMERA_INFORMATION mavlink messages. Is it normal to take so long to establish the camera connection?

When I do `ffplay rtsp://192.168.2.112:8554/live` it works great. From the command in the readme, the stream-url is just the raw IP, which is then the `uri` in the VIDEO_STREAM_INFORMATION - 192.168.2.112 . This is wrong I'm assuming, and should be the full rtsp link. 

![Screenshot from 2024-11-10 14-32-58](https://github.com/user-attachments/assets/7abe3476-4ba6-4bf2-ac5f-9102fc243679)

**Comment by lherlein** [comment]
Using the full rtsp url in the command worked. I'm having other issues but will troubleshoot and open a new issue if needed. I'll also open a PR to update the camera_manager command in the readme.

**Comment by lherlein** [comment]
Thanks so much for the help!

**Comment by julianoes** [comment]
Thanks! Sorry about the wrong readme.
